colors:
  tags: green
  title: blue
  issue_id: red
labels:
  # if any issue has one of these labels, 
  # they will be shown in this list
  priority_labels:
    - urgent
    - todo
  # if a task has a deadline, it is considered priority, also
  # if the due date is before this time (regardless of having urgent/todo label)
  priority_timeframe: 48hrs
gitlab.com:
  credential:
    service: gitlab.com
    username: myusername_in_keyring_entry_pat
  repositories:
     # a great set of unicode characters are here - https://www.compart.com/en/unicode/category/So
    - id: 🅆
      color: blue
      project_id: someorg%2Fmy-tasks
      defaults:
        for_new_tasks: true
    - id: 🄿
      color: green    
      project_id: someorg%2Fmy-tasks
      defaults:
        for_new_tasks: true
