name: release
on:
  push:
    tags:
      - v*

env:
  PROJECT_NAME: tskmstr
  REPO_NAME: rbuckland/tskmstr
  
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [x86_64-linux, aarch64-linux, aarch64-macos, x86_64-macos, x86_64-windows, aarch64-windows, x86_64-freebsd]
        include:

        - build: x86_64-linux
          os: ubuntu-22.04
          rust: nightly
          target: x86_64-unknown-linux-gnu
          artifact_name: tskmstr
          asset_name: tskmstr-linux-amd64          
        - build: aarch64-linux
          os: ubuntu-22.04
          rust: nightly
          target: aarch64-unknown-linux-gnu
          cross: true
          artifact_name: tskmstr
          asset_name: tskmstr-linux-aarch64

        - build: x86_64-macos
          os: macos-latest
          rust: nightly
          target: x86_64-apple-darwin
          cross: false
          artifact_name: tskmstr
          asset_name: tskmstr-osx-amd64
        - build: aarch64-macos
          os: macos-latest
          rust: nightly
          cross: true
          target: aarch64-apple-darwin
          artifact_name: tskmstr
          asset_name: tskmstr-osx-aarch64          

        - build: x86_64-windows
          os: windows-2019
          rust: nightly
          target: x86_64-pc-windows-msvc
          cross: false
          artifact_name: tskmstr.exe
          asset_name: tskmstr-windows-amd64
        - build: aarch64-windows
          os: windows-2019
          rust: nightly
          target: aarch64-pc-windows-msvc
          cross: true
          artifact_name: tskmstr.exe
          asset_name: tskmstr-windows-aarch64

        - build: x86_64-freebsd
          os: ubuntu-22.04
          rust: nightly
          cross: true
          target: x86_64-unknown-freebsd
          artifact_name: tskmstr
          asset_name: tskmstr-freebsd-amd64
    steps:
      - name: Checkout Source
        uses: actions/checkout@master
      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: test
          args: --release --locked --target ${{ matrix.target }}

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked --target ${{ matrix.target }}

      - name: Strip release binary (linux and macos)
        if: matrix.build == 'x86_64-linux' || matrix.build == 'x86_64-macos'
        run: strip "target/${{ matrix.target }}/release/${{ matrix.artifact_name }}"

      - name: Strip release binary (arm)
        if: matrix.build == 'aarch64-linux'
        run: |
          docker run --rm -v \
            "$PWD/target:/target:Z" \
            rustembedded/cross:${{ matrix.target }} \
            aarch64-linux-gnu-strip \
            /target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true 
